# Generated by Django 3.1.7 on 2021-10-09 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missandmr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contestant',
            name='proofOfPayment',
            field=models.ImageField(default='', upload_to='images/proof-of-payment'),
        ),
    ]
