# Generated by Django 3.1.7 on 2021-10-09 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missandmr', '0002_contestant_proofofpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='contestant',
            name='status',
            field=models.TextField(choices=[('Not Paid', 'Not Paid'), ('Paid', 'Paid')], default='Not Paid', max_length=20),
        ),
        migrations.AlterField(
            model_name='contestant',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=10),
        ),
        migrations.AlterField(
            model_name='contestant',
            name='picture',
            field=models.ImageField(default='', upload_to='images/'),
        ),
    ]
