# Generated by Django 3.1.7 on 2021-10-11 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missandmr', '0003_auto_20211009_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='contestant',
            name='email',
            field=models.CharField(default='', max_length=455),
        ),
    ]
