# Generated by Django 3.1.7 on 2021-10-11 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missandmr', '0004_contestant_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contestant',
            name='proofOfPayment',
        ),
        migrations.AddField(
            model_name='contestant',
            name='amount',
            field=models.CharField(default='N5,000', max_length=455),
        ),
    ]
