# Generated by Django 3.1.7 on 2021-10-11 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missandmr', '0005_auto_20211011_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contestant',
            name='amount',
            field=models.CharField(default='N5,000', editable=False, max_length=455),
        ),
        migrations.AlterField(
            model_name='contestant',
            name='status',
            field=models.TextField(choices=[('Not Paid', 'Not Paid'), ('Paid', 'Paid')], default='Paid', max_length=20),
        ),
    ]
