# Generated by Django 3.1.7 on 2021-10-11 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missandmr', '0006_auto_20211011_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contestant',
            name='amount',
            field=models.CharField(default='N5,000', max_length=455),
        ),
    ]
